
name: Azure OIDC Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write  
  contents: read   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: IDENTITY

      - name: Azure CLI - Show current account
        run: az account show

      - name: set aks context
        uses: azure/aks-set-context@v1
        with:
          resource-group: Mygroup
          cluster-name: myaks
      
      - name: login to acr
        run: az acr login --name myownnregistry
         
         
      - name: build and push docker image
        run: | 
          docker build -t myownnregistry.azurecr.io/myapp:v1 .
          docker push myownnregistry.azurecr.io//myapp:v1 

      - name: deploy to aks
        run : |
          kubectl set image deployment/myapp myapp=myownnregistry.azurecr.io/myapp:v1